module.exports = [
    {
    name: 'Fatty',
    frame: 'Surly Wednesday',
    fork: 'Surly',
    rims: 'My Other Brother Darryl',
    hubs: 'Novatec',
    tires: 'Surly Nate 26 x 3.8',
    handlebars: '800mm Risers',
    headset: 'Cane Creek',
    crankset: 'Sram GX',
    pedals: 'HT flat',
    cassette: 'Sram GX Eagle 12s',
    derailleur: 'Sram GX Eagle 12s',
    brakes: 'BB5 mechanical',
    shifters: 'Sram GX Eagle 12s',
    saddle: 'Stock',
    seatpost: 'Stock',
    stem: 'Stock',
    frontbag: 'BXB Goldback',
    framebag: 'n/a',
    rearbag: 'n/a',
    img: '',
    },
    {
    name: 'Extra',
    frame: 'Omnium Titanium',
    fork: 'Omnium',
    rims: 'Nextie Carbon',
    hubs: 'White Industries rear, SP dynamo front',
    tires: 'Schwalbe Racing Ralph rear, Rocket Ron front',
    handlebars: 'Protaper 800mm',
    headset: 'White Industries',
    crankset: 'Easton EC90 SL Carbon',
    pedals: 'HT flat',
    cassette: 'Shimano XT 12s',
    derailleur: 'Shimano XT 12s',
    brakes: 'Shimano MT420 hydro',
    shifters: 'Shimano XT 12s',
    saddle: "Selle Italia Flite 90's",
    seatpost: 'Bike Yoke Rascal SL dropper',
    stem: 'Thomson X4',
    frontbag: 'BXB Goldback',
    framebag: 'Rockgeist Custom',
    rearbag: 'Swift Industries EDC',
    img: '',
    },
    {
    name: 'Fast Boy',
    frame: 'Salsa Stormchaser',
    fork: 'Salsa Stormchaser',
    rims: 'Velocity Blunt SS',
    hubs: 'DT 350 rear, SP Dynamo front',
    tires: 'Rene Herse Oracle Ridge 700x48',
    handlebars: 'Soma Hwy One 46cm',
    headset: 'Cane Creek',
    crankset: 'Easton EA90',
    pedals: 'HT flat',
    cassette: 'E-Thirteen Helix 9-46t',
    derailleur: 'Shimano GRX 812',
    brakes: 'Shimano GRX',
    shifters: 'Shimano GRX',
    saddle: 'Fabric Scoop',
    seatpost: 'One Up dropper',
    stem: 'Thomson x4',
    frontbag: 'n/a',
    framebag: 'Custom',
    rearbag: 'n/a',
    img: '',
    }
]